/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_JNICommons */

#ifndef _Included_org_opensearch_knn_jni_JNICommons
#define _Included_org_opensearch_knn_jni_JNICommons
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_JNICommons
 * Method:    storeVectorData
 * Signature: (J[[FJJ)
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_JNICommons_storeVectorData
  (JNIEnv *, jclass, jlong, jobjectArray, jlong);

/*
 * Class:     org_opensearch_knn_jni_JNICommons
 * Method:    storeVectorData
 * Signature: (J[[FJJ)
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_JNICommons_storeByteVectorData
  (JNIEnv *, jclass, jlong, jobjectArray, jlong);

/*
 * Class:     org_opensearch_knn_jni_JNICommons
 * Method:    freeVectorData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_JNICommons_freeVectorData
  (JNIEnv *, jclass, jlong);

/*
* Class:     org_opensearch_knn_jni_JNICommons
* Method:    freeVectorData
* Signature: (J)V
*/
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_JNICommons_freeByteVectorData
(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
