/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SIMDEncoding */

#ifndef _Included_org_opensearch_knn_jni_SIMDEncoding
#define _Included_org_opensearch_knn_jni_SIMDEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SIMDEncoding
 * Method:    convertFP32ToFP16
 * Signature: ([F[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SIMDEncoding_convertFP32ToFP16
  (JNIEnv *, jclass, jfloatArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
