/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SIMDNativeLibraryLoader */

#ifndef _Included_org_opensearch_knn_jni_SIMDNativeLibraryLoader
#define _Included_org_opensearch_knn_jni_SIMDNativeLibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SIMDNativeLibraryLoader
 * Method:    isSIMDSupportedNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SIMDNativeLibraryLoader_isSIMDSupportedNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
