/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SimdFp16 */

#ifndef _Included_org_opensearch_knn_jni_SimdFp16
#define _Included_org_opensearch_knn_jni_SimdFp16
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SimdFp16
 * Method:    isSIMDSupportedNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SimdFp16_isSIMDSupportedNative
  (JNIEnv *, jclass);

/*
 * Class:     org_opensearch_knn_jni_SimdFp16
 * Method:    convertFP32ToFP16
 * Signature: ([F[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SimdFp16_encodeFp32ToFp16
  (JNIEnv *, jclass, jfloatArray, jbyteArray, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdFp16
 * Method:    convertFP16ToFP32
 * Signature: ([B[FII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SimdFp16_decodeFp16ToFp32
  (JNIEnv *, jclass, jbyteArray, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
