/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SIMDDecoding */

#ifndef _Included_org_opensearch_knn_jni_SIMDDecoding
#define _Included_org_opensearch_knn_jni_SIMDDecoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SIMDDecoding
 * Method:    convertFP16ToFP32
 * Signature: ([B[FII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensearch_knn_jni_SIMDDecoding_convertFP16ToFP32
  (JNIEnv *, jclass, jbyteArray, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
