/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_index_JNIService */

#ifndef _Included_org_opensearch_knn_index_JNIService
#define _Included_org_opensearch_knn_index_JNIService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    createIndex
 * Signature: ([I[[FLjava/lang/String;Ljava/util/Map;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_index_JNIService_createIndex
  (JNIEnv *, jclass, jintArray, jobjectArray, jstring, jobject, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    createIndexFromTemplate
 * Signature: ([I[[FLjava/lang/String;[BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_index_JNIService_createIndexFromTemplate
  (JNIEnv *, jclass, jintArray, jobjectArray, jstring, jbyteArray, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    loadIndex
 * Signature: (Ljava/lang/String;Ljava/util/Map;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_index_JNIService_loadIndex
  (JNIEnv *, jclass, jstring, jobject, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    queryIndex
 * Signature: (J[FILjava/lang/String;)[Lorg/opensearch/knn/index/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensearch_knn_index_JNIService_queryIndex
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    free
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_index_JNIService_free
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    initLibrary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_index_JNIService_initLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    trainIndex
 * Signature: (Ljava/util/Map;IJLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_opensearch_knn_index_JNIService_trainIndex
  (JNIEnv *, jclass, jobject, jint, jlong, jstring);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    transferVectors
 * Signature: (J[[F)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_index_JNIService_transferVectors
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     org_opensearch_knn_index_JNIService
 * Method:    freeVectors
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_index_JNIService_freeVectors
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
