/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.knn.index.remote;

import org.opensearch.cluster.ClusterName;
import org.opensearch.cluster.metadata.RepositoryMetadata;
import lombok.Getter;
import org.opensearch.index.IndexSettings;
import org.opensearch.knn.index.codec.nativeindex.model.BuildIndexParams;
import org.opensearch.knn.index.codec.nativeindex.remote.RemoteIndexBuildStrategy;
import org.opensearch.knn.index.codec.util.KNNCodecUtil;
import org.opensearch.knn.index.vectorvalues.KNNVectorValues;

import java.io.IOException;
import java.util.Map;

import static org.opensearch.knn.common.KNNConstants.BUCKET;
import static org.opensearch.knn.common.KNNConstants.S3;

@Getter
public abstract class RemoteBuildRequest {
    public String repositoryType;
    public String containerName;
    public String vectorPath;
    public String docIdPath;
    public String tenantId;
    public int dimension;
    public int docCount;
    public String dataType;
    public String engine;
    public Map<String, Object> indexParameters;

    /**
     * Construct the RemoteBuildRequest object for the index build request.
     * Regardless of the Client implementation, the remote build service will need these parameters to build the index.
     * This method being included in the interface ensures that the request parameters will be set for each Client implementation to use or transform for its needs.
     * @param indexSettings Index settings
     * @param indexInfo Index parameters
     * @param repositoryMetadata Metadata of the repository containing the index
     * @param blobName File name generated by the Build Strategy with a UUID
     */
    public RemoteBuildRequest(
        IndexSettings indexSettings,
        BuildIndexParams indexInfo,
        RepositoryMetadata repositoryMetadata,
        String blobName
    ) throws IOException {
        String repositoryType = repositoryMetadata.type();
        String containerName;
        switch (repositoryType) {
            case S3 -> containerName = repositoryMetadata.settings().get(BUCKET);
            default -> throw new IllegalArgumentException(
                "Repository type " + repositoryType + " is not supported by the remote build service"
            );
        }
        String vectorDataType = indexInfo.getVectorDataType().getValue();

        KNNVectorValues<?> vectorValues = indexInfo.getKnnVectorValuesSupplier().get();
        KNNCodecUtil.initializeVectorValues(vectorValues);
        assert (vectorValues.dimension() > 0);

        Map<String, Object> indexParameters = indexInfo.getKnnEngine().getRemoteIndexingParameters(indexInfo);

        this.repositoryType = repositoryType;
        this.containerName = containerName;
        this.vectorPath = blobName + RemoteIndexBuildStrategy.VECTOR_BLOB_FILE_EXTENSION;
        this.docIdPath = blobName + RemoteIndexBuildStrategy.DOC_ID_FILE_EXTENSION;
        this.tenantId = indexSettings.getSettings().get(ClusterName.CLUSTER_NAME_SETTING.getKey());
        this.dimension = vectorValues.dimension();
        this.docCount = indexInfo.getTotalLiveDocs();
        this.dataType = vectorDataType;
        this.engine = indexInfo.getKnnEngine().getName();
        this.indexParameters = indexParameters;
    }
}
