name: Publish snapshots to maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '1.*'
      - '2.*'

jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 11
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Load secret
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          MAVEN_SNAPSHOTS_S3_REPO: op://opensearch-infra-secrets/maven-snapshots-s3/repo
          MAVEN_SNAPSHOTS_S3_ROLE: op://opensearch-infra-secrets/maven-snapshots-s3/role

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          role-to-assume: ${{ env.MAVEN_SNAPSHOTS_S3_ROLE }}
          aws-region: us-east-1

      - name: publish snapshots to maven
        run: |
          # For zip
          ./gradlew publishPluginZipPublicationToSnapshotsRepository
